"""Draw Argos, and write the character file the window reads.

Why a script rather than 24 hand-typed grids
--------------------------------------------
The frames share almost everything: one dog, one silhouette, a handful of parts
that move. Typed out 24 times, a change to the muzzle is 24 edits and the frames
drift apart on the first one somebody misses. Here a pose is a choice of head,
tail and legs, and each part is authored once.

The fills are authored; the outline is not. Every frame gets its dark edge
computed from the shape, which keeps the silhouette even and is the method
the redesign settled on: author the colour, let the script find the border.

Run it from anywhere; it rewrites argos.txt beside itself:

    python argos/ui/sprites/make_sprites.py

argos.txt stays the committed artifact, exactly as icons/icon.png does next to
icons/make_icon.py: the window and the tests read the text, never this file.
"""

from __future__ import annotations

from pathlib import Path

SIZE = 32
OUT = Path(__file__).resolve().parent / "argos.txt"

Frame = list[list[str]]

HEADER = """\
# Argos, 32x32, side profile facing right. German Shepherd: erect pointed
# ears, a long muzzle, a black saddle over a tan coat, a low bushy tail.
#
# GENERATED by make_sprites.py in this directory. Edit the parts there and
# re-run it; editing the rows below by hand is lost on the next run.
#
# One character per pixel:
#   .  transparent          k  outline #160F0A     w  coat #D99347
#   g  coat shade #A96B2C   a  saddle/ears #2A2119  o  saddle shade #15100C
#   b  DataHub blue         d  blue shade          r  red
#
# Red is state, never decoration, and no frame here uses r at all. The collar
# is blue in the art and the renderer is the only thing that turns it red, when
# a finding is live. An open mouth is drawn with the outline colour, because a
# mouth is a hole and a red one made the bark read as an injured dog.
#
# A `# name` line opens a frame and every line after it is a row. Every frame is
# 32 rows of exactly 32 characters, which tests/test_argos.py checks, so a
# mistyped row fails the suite rather than the window.
#
# Legs are two clusters (fore near the chest, hind near the haunch), each a
# near leg ('w') beside a far leg ('g') so the animal reads as four legs rather
# than two. Built from rigid blocks that only ever move as a whole between
# frames, not bent within one: a hand-drawn diagonal reach put pixels next to
# only their diagonal neighbours, and the auto-outline pass (4-directional
# adjacency) then outlined each one on its own, rendering as a trail of
# separate floating squares instead of a limb.
"""


def grid() -> Frame:
    """A blank transparent frame."""
    return [["." for _ in range(SIZE)] for _ in range(SIZE)]


def stamp(target: Frame, art: str, top: int, left: int = 0) -> None:
    """Paint a block of art onto the frame, treating '.' as see-through.

    Left as see-through, rather than opaque, so parts can overlap: the tail is
    drawn under the torso and the head over the shoulder without either having
    to know the other's shape.
    """
    for y, line in enumerate(art.strip("\n").split("\n")):
        for x, char in enumerate(line):
            if char == ".":
                continue
            row, col = top + y, left + x
            if 0 <= row < SIZE and 0 <= col < SIZE:
                target[row][col] = char


def outline(frame: Frame) -> Frame:
    """Grow a one-pixel dark edge around everything solid.

    Orthogonal neighbours only. Including diagonals fattens every corner, and
    at this size the corners are most of the character's shape.
    """
    out = [row[:] for row in frame]
    for y in range(SIZE):
        for x in range(SIZE):
            if frame[y][x] != ".":
                continue
            for dy, dx in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                ny, nx = y + dy, x + dx
                if 0 <= ny < SIZE and 0 <= nx < SIZE and frame[ny][nx] not in ".k":
                    out[y][x] = "k"
                    break
    return out


# --- head ----------------------------------------------------------------
#
# Ear up, eye forward, muzzle out to the right. Kept close to full skull
# height for most of its length and blunted in the last two rows: a first pass
# tapered a wide skull down to almost nothing over six rows while still
# reaching the frame's far edge, and a wedge that thin and that long read as a
# beak rather than a snout.

HEAD = """
.................aa...aa........
................aaaa.aaaa.......
................aaaa.aaaa.......
...............aaawwwaaaw.......
...............awwwwwwwww.......
..............wwwwwwwwwwww......
..............wwwwwwwwwwww......
.............wwwwwkkwwwwwwww....
.............wwwwwkkwwwwwaaaak..
.............wwwwwwwwwwwwaaaak..
..............wwwwwwwwwwwaaak...
...............wwwwwwwwwaa......
"""

#: Eye shut. Nothing else moves: a blink that shifted the skull would read as
#: a flinch.
HEAD_BLINK = """
.................aa...aa........
................aaaa.aaaa.......
................aaaa.aaaa.......
...............aaawwwaaaw.......
...............awwwwwwwww.......
..............wwwwwwwwwwww......
..............wwwwwwwwwwww......
.............wwwwwwwwwwwwww.....
.............wwwwwkkwwwwwaaaak..
.............wwwwwwwwwwwwaaaak..
..............wwwwwwwwwwwaaak...
...............wwwwwwwwwaa......
"""

#: Head cocked: the ear folds over and the whole skull leans back. What
#: curiosity looks like when there is no room for an eyebrow.
HEAD_TILT = """
..............aa...aa...........
.............aaaa.aaaa..........
.............aaaa.aaaa..........
............aaawwwaaaw..........
............awwwwwwwww..........
...........wwwwwwwwwwww.........
...........wwwwwwwwwwww.........
..........wwwwwkkwwwwwwww.......
..........wwwwwkkwwwwwaaaak.....
..........wwwwwwwwwwwwaaaak.....
...........wwwwwwwwwwwaaak......
............wwwwwwwwwaa.........
"""

#: Open jaw. The mouth opens from the same hinge the closed muzzle tapers from,
#: upper lip in the marking colour and the gap between the jaws in the outline
#: colour: a mouth is a hole, and this is where the light does not reach. It was
#: red once, which was the one place red occurred naturally in the character and
#: still the wrong call: at 32 pixels a red muzzle reads as a bleeding dog, not
#: a barking one, and red already means a live finding on the collar.
HEAD_BARK = """
................aa...aa.........
...............aaaa.aaaa........
...............aaaa.aaaa........
..............aaawwwaaaw........
..............awwwwwwwww........
.............wwwwwwwwwwww.......
.............wwwwwwwwwwww.......
............wwwwwkkwwwwwwaaa....
............wwwwwkkwwwwaakkkaak.
............wwwwwwwwwwkkkkkkak..
............wwwwwwwwwaaaaaak....
.............wwwwwwwwwaa........
"""

#: Nose to the floor, following something.
HEAD_SNIFF = """
..................aa...aa.......
.................aaaa.aaaa......
.................aaaa.aaaa......
................aaawwwaaaw.......
................awwwwwwwww.......
...............wwwwwwwwwwww.....
..............wwwwwwwwwwwww.....
..............wwwwwkkwwwwwww....
..............wwwwwkkwwwwaaaak..
..............wwwwwwwwwwwaaaak..
...............wwwwwwwwwwaaak...
................wwwwwwwwaa.......
"""

#: Head up and turning, looking for something that is not there.
HEAD_SEARCH = """
............aa...aa.............
...........aaaa.aaaa............
...........aaaa.aaaa............
..........aaawwwaaaw............
..........awwwwwwwww............
.........wwwwwwwwwwww...........
.........wwwwwwwwwwww...........
........wwwwwkkwwwwwwww.........
........wwwwwkkwwwwwaaaak.......
........wwwwwwwwwwwwaaaak.......
.........wwwwwwwwwwwaaak........
..........wwwwwwwwwaa...........
"""

# --- asleep ------------------------------------------------------------------
#
# The one pose that is not the standing rig with a part swapped, because a
# sleeping dog is not a standing dog with different legs. The first attempt was
# exactly that (the standing head and torso pushed down three rows, the legs
# replaced by a flat slab) and it read as a dog standing in a hole. A dog asleep
# is a low mound: the haunch at one end, the back sloping down to a head laid on
# outstretched forepaws, and the tail curled around against the ground.

#: Head laid low, eye shut, ears still up. Shepherds sleep with their ears up
#: and folding them here lost the breed in the only pose it holds for minutes.
SLEEP_HEAD = """
..................aa...aa.......
.................aaaa.aaaa......
.................aaaa.aaaa......
................aaawwwaaaw......
................awwwwwwwww......
...............wwwwwkkwwwww.....
...............wwwwwwwwwwwww....
...............wwwwwwwwwwwaaaak.
................wwwwwwwwwaaaaak.
.................wwwwwwwaaaak...
"""

#: Haunch, back and the forelegs stretched out in front. The last two rows are
#: belly and legs as one mass on purpose: at this size a lying dog's legs are
#: not separable from its underside, and drawing them apart made a caterpillar.
#:
#: The left edge stops at column 4 rather than at the frame's, to leave the tail
#: somewhere to be. A body drawn out to the edge swallowed it: haunch and tail
#: are both the saddle colour, so an overlapping tail is not a tail, it is two
#: pixels nobody can see.
SLEEP_BODY = """
..........aaaaaaaa..............
........aaaaaaaaaaaa............
......aaaaaaaaaaaaaaa...........
.....aaaaaaaaaaaaaaaa...........
.....aaaaaaaaaaaaaaaw...........
....waaaaaaaaaaaaawwww..........
....wwwaaaaaaaawwwwwwww.........
....gwwwwwwwwwwwwwwwwwwwwwwwww..
....ggwwwwwwwwwwwwwwwwwwwwwww...
"""

#: The tail curled around the rear and down onto the ground, drawn after the
#: body so the part that overlaps the haunch is hidden and only the curl shows.
SLEEP_TAIL = """
..aaaa..........................
.aaaaao.........................
aaaaoo..........................
aaoo............................
"""

#: The collar, at the neck rather than at the standing rig's throat row. Most of
#: it is behind the head; the few pixels that show are the point, because a dog
#: that loses its collar in one pose stops being the same dog.
SLEEP_COLLAR = """
............bbbb................
............dddd................
"""

#: One row of ribcage, added to the second sleeping frame only. That is the
#: whole breath: raising the whole body instead reads as the dog levitating,
#: and moving the head with it reads as a flinch.
SLEEP_BREATH = """
.........aaaaaaaa...............
"""

# --- body ------------------------------------------------------------------

#: The saddle is the breed's signature: black over the back and shoulders,
#: fading to tan at the flank.
TORSO = """
.....aaaaaaaaaaaaaaa............
...aaaaaaaaaaaaaaaaaa...........
..waaaaaaaaaaaaaaaaaaw..........
..waaaaaaaaaaaaaaaaaww..........
..wwaaaaaaaaaaaaaawwww..........
..wwwwaaaaaaaaawwwwwww..........
..gwwwwwwwwwwwwwwwwwww..........
..ggwwwwwwwwwwwwwwwwww..........
"""

#: The collar. Blue is identity; it only turns red when the renderer repaints
#: it for a live finding.
COLLAR = """
.............bbbbbbbb...........
.............dddddddd...........
"""

#: Tails, drawn over the torso's back end. Carried low and bushy at rest, the
#: way a shepherd holds it.
TAIL_LOW = """
................................
.aa.............................
aaao............................
aaoo............................
.aoo............................
..oo............................
"""
TAIL_MID = """
..aa............................
.aaao...........................
aaaoo...........................
aaoo............................
.oo.............................
................................
"""
TAIL_WAG = """
...aaa..........................
..aaaao.........................
.aaaaoo.........................
.aaoo...........................
..oo............................
................................
"""
TAIL_DOWN = """
................................
................................
.aa.............................
.aaoo...........................
..aoo...........................
..ooo...........................
"""

# --- legs --------------------------------------------------------------------

LEG_CLUSTER = ["wwwggg", "wwwggg", "wwwggg", "wwwggg", "www...", "www..."]


def leg_frame(
    fore_col: int,
    hind_col: int,
    *,
    lift: str | None = None,
    shorten: str | None = None,
) -> str:
    """Stamp a fore and a hind leg cluster at the given columns.

    ``lift`` raises one cluster ("fore" or "hind") a row and a half off the
    ground, for the paw poses: sniffing, tugging, pointing at a dropped file.

    ``shorten`` truncates one cluster to its top three rows, planted at the
    same spot rather than folded elsewhere. A folded haunch drawn a couple of
    rows below the tail left a one-row gap between the two shapes, which the
    outline pass then rims as two separate pieces: a small fragment floating
    beside the dog rather than a leg tucked under it. Shortening in place is
    guaranteed to meet whatever sits above it, because it is the same column
    that shape was already drawn to meet.
    """
    rows: list[list[str]] = [["." for _ in range(SIZE)] for _ in range(6)]
    for which, col in (("fore", fore_col), ("hind", hind_col)):
        rise = 2 if which == lift else 0
        cluster = LEG_CLUSTER[:3] if which == shorten else LEG_CLUSTER
        for y, cluster_row in enumerate(cluster):
            target = y - rise
            if target < 0:
                continue
            for x, ch in enumerate(cluster_row):
                if ch != "." and 0 <= col + x < SIZE:
                    rows[target][col + x] = ch
    return "\n".join("".join(row) for row in rows)


#: Standing square: fore legs under the shoulder, hind legs under the haunch.
LEGS_STAND = leg_frame(fore_col=4, hind_col=17)
#: Splayed apart, the widest part of a trot's stride.
LEGS_WALK_A = leg_frame(fore_col=1, hind_col=20)
#: Passing under the body, neutral.
LEGS_WALK_B = LEGS_STAND
#: Converged near the centre, the other extreme of the stride.
LEGS_WALK_C = leg_frame(fore_col=8, hind_col=13)
LEGS_WALK_D = LEGS_WALK_B
#: Sitting: the haunch is a shortened standing hind leg, not a fold elsewhere.
LEGS_SIT = leg_frame(fore_col=4, hind_col=17, shorten="hind")
#: Folded up under the body, for the airborne half of the bark. Both clusters
#: are cut to their top rows and pulled inward: legs that stayed at full length
#: while the sprite was lifted read as a dog on stilts, not a dog off the floor.
LEGS_TUCK = """
.....wwwggg....wwwggg...........
.....wwwggg....wwwggg...........
.....www.......www..............
................................
................................
................................
"""
#: One fore paw lifted, for sniffing, tugging and pointing at things.
LEGS_PAW = leg_frame(fore_col=4, hind_col=17, lift="fore")

#: Where each part is stamped, top row first.
ROWS = {"tail": 16, "torso": 15, "head": 2, "collar": 14, "legs": 23}


def compose(head: str, legs: str, tail: str) -> list[str]:
    """Build one standing frame from its parts, then find its outline.

    Order matters: the tail goes down first so the torso sits in front of it,
    the head next so it overlaps the shoulder the way a big head does, and the
    collar last so it reads as worn rather than swallowed.
    """
    frame = grid()
    stamp(frame, tail, ROWS["tail"])
    stamp(frame, TORSO, ROWS["torso"])
    stamp(frame, head, ROWS["head"])
    stamp(frame, COLLAR, ROWS["collar"])
    stamp(frame, legs, ROWS["legs"])
    return ["".join(row) for row in outline(frame)]


#: Where the sleeping parts are stamped. Their own rows, not ``ROWS``: this pose
#: has no torso, no leg clusters and no throat, so borrowing the standing rig's
#: offsets would only make the two look related in the source.
SLEEP_ROWS = {"tail": 25, "body": 20, "breath": 19, "collar": 22, "head": 17}


def sleep_pose(*, breathing: bool) -> list[str]:
    """Build one sleeping frame; ``breathing`` adds the raised ribcage row."""
    frame = grid()
    stamp(frame, SLEEP_TAIL, SLEEP_ROWS["tail"])
    stamp(frame, SLEEP_BODY, SLEEP_ROWS["body"])
    if breathing:
        stamp(frame, SLEEP_BREATH, SLEEP_ROWS["breath"])
    stamp(frame, SLEEP_COLLAR, SLEEP_ROWS["collar"])
    stamp(frame, SLEEP_HEAD, SLEEP_ROWS["head"])
    return ["".join(row) for row in outline(frame)]


#: Every frame the window can draw, and what it is made of. The names are the
#: contract: argos.js and walk.js index this file by them, and
#: tests/test_argos.py fails if either side grows a name the other does not have.
FRAMES: dict[str, list[str]] = {
    "idle_a": compose(HEAD, LEGS_STAND, TAIL_MID),
    "idle_b": compose(HEAD, LEGS_STAND, TAIL_LOW),
    "blink": compose(HEAD_BLINK, LEGS_STAND, TAIL_MID),
    "walk_a": compose(HEAD, LEGS_WALK_A, TAIL_LOW),
    "walk_b": compose(HEAD, LEGS_WALK_B, TAIL_MID),
    "walk_c": compose(HEAD, LEGS_WALK_C, TAIL_LOW),
    "walk_d": compose(HEAD, LEGS_WALK_D, TAIL_MID),
    "sniff_a": compose(HEAD_SNIFF, LEGS_STAND, TAIL_MID),
    "sniff_b": compose(HEAD_SNIFF, LEGS_PAW, TAIL_LOW),
    # The bark is a jump: planted and shouting, then off the floor with the legs
    # tucked. The lift itself belongs to the renderer, which raises the sprite
    # on the second frame, so the two stay in step without a shared clock.
    "alert_a": compose(HEAD_BARK, LEGS_STAND, TAIL_WAG),
    "alert_b": compose(HEAD_BARK, LEGS_TUCK, TAIL_WAG),
    "tilt_a": compose(HEAD_TILT, LEGS_STAND, TAIL_MID),
    "tilt_b": compose(HEAD_TILT, LEGS_STAND, TAIL_DOWN),
    "sleep_a": sleep_pose(breathing=False),
    "sleep_b": sleep_pose(breathing=True),
    "sit": compose(HEAD, LEGS_SIT, TAIL_DOWN),
    "scribble_a": compose(HEAD_SNIFF, LEGS_PAW, TAIL_MID),
    "scribble_b": compose(HEAD_SNIFF, LEGS_STAND, TAIL_DOWN),
    "tug_a": compose(HEAD_TILT, LEGS_PAW, TAIL_WAG),
    "tug_b": compose(HEAD_TILT, LEGS_STAND, TAIL_LOW),
    "wag_a": compose(HEAD, LEGS_STAND, TAIL_WAG),
    "wag_b": compose(HEAD, LEGS_STAND, TAIL_LOW),
    "search_a": compose(HEAD_SEARCH, LEGS_STAND, TAIL_MID),
    "search_b": compose(HEAD_SEARCH, LEGS_PAW, TAIL_DOWN),
}


def render() -> str:
    """The character file, header and all."""
    parts = [HEADER]
    for name, rows in FRAMES.items():
        parts.append(f"\n# {name}\n" + "\n".join(rows) + "\n")
    return "".join(parts)


def main() -> None:
    """Write the character file, failing loudly if a frame came out malformed."""
    for name, rows in FRAMES.items():
        assert len(rows) == SIZE, f"{name} has {len(rows)} rows"
        for row in rows:
            assert len(row) == SIZE, f"{name} has a row of {len(row)} characters"
    OUT.write_text(render())
    print(f"wrote {len(FRAMES)} frames to {OUT}")


if __name__ == "__main__":
    main()
