"""Bundle every pixel the page draws into one file `site/` can serve alone.

Why this exists
---------------
The page used to read the character straight out of `argos/ui/`, which is the
one copy of that art and exactly where it should be read from (site/CLAUDE.md
rule 1). That works locally, where the server root is the repository root, and
it silently fails in production: the deployment is served with `site/` as its
root, so `../argos/` is outside it, the fetch 404s, and the page renders
perfectly with no dog on it. Nothing errors, which is why it survived a review
and a deploy (D-139).

So the art is inlined here instead, and the guarantee that it cannot go stale
moves from a rule somebody remembers to a test that fails: `tests/test_site.py`
runs this generator and compares its output against the committed file, so a
redrawn leg that never reaches the page breaks the suite.

Inlining also removes the fetch entirely, which means the page now works under
`file://` as well as behind a server.

    python site/art/make_pixels.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
RENDERER = ROOT / "argos" / "ui" / "sprites.js"
CHARACTER = ROOT / "argos" / "ui" / "sprites" / "argos.txt"
ORNAMENTS = HERE / "ornaments.txt"
OUT = HERE.parent / "pixels.js"

HEADER = """/**
 * Every pixel the documentation page draws, in one file.
 *
 * GENERATED by site/art/make_pixels.py. Do not edit: run the generator.
 *
 * Three things are bundled here, and the reason they are bundled rather than
 * fetched is that the deployment's root is `site/`, so anything outside this
 * directory is unreachable from the served page (D-139):
 *
 *   ArgosSprites            the renderer, verbatim from argos/ui/sprites.js
 *   ArgosSprites.ART        the character, verbatim from argos/ui/sprites/argos.txt
 *   ArgosSprites.ORNAMENTS  the Roman ornaments, from site/art/ornaments.txt
 *
 * `ArgosSprites.load()` below still fetches a path that does not exist here.
 * Nothing on this page calls it: the page reads `ART` instead. It is left in
 * place because this section is copied verbatim, and a generator that edits the
 * code it copies is a generator that can disagree with the original.
 *
 * The two palettes are deliberately separate. The character indexes DataHub's
 * blues and tans; the ornaments index the page's own stone and caramel, and
 * they collide on the letters `b` and `d`, which mean different colours in each.
 */
"""

#: The ornaments' palette, kept beside the art rather than in the stylesheet:
#: canvas takes no custom properties, and a second hand-maintained copy of these
#: values is exactly the drift this generator exists to prevent.
ORNAMENT_PALETTE = {
    "k": "#2b1d13",
    "l": "#f3e9d6",
    "s": "#e0d0b0",
    "d": "#c6ae8b",
    "c": "#c08a4a",
    "b": "#9a5d21",
    "r": "#6e1f26",
}


def build() -> str:
    """The whole bundle, as the text that should be on disk."""
    renderer = RENDERER.read_text()
    parts = [
        HEADER,
        renderer.rstrip(),
        "",
        f"window.ArgosSprites.ART = {json.dumps(CHARACTER.read_text())};",
        "",
        f"window.ArgosSprites.ORNAMENTS = {json.dumps(ORNAMENTS.read_text())};",
        "",
        f"window.ArgosSprites.ORNAMENT_PALETTE = {json.dumps(ORNAMENT_PALETTE, indent=2)};",
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    """Write the bundle, and say how big it got."""
    text = build()
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text) // 1024} KB)")


if __name__ == "__main__":
    main()
